<!doctype html>
<html>
    <head>
        <title>Something is Wrong..</title>
    </head>
    <body>
        <center><h1>Server Error.</h1></center>
        <hr>
        <center>powered by look</center>
        <!-- a padding to disable MSIE and Chrome friendly error page -->
        <!-- a padding to disable MSIE and Chrome friendly error page -->
        <!-- a padding to disable MSIE and Chrome friendly error page -->
        <!-- a padding to disable MSIE and Chrome friendly error page -->
        <!-- a padding to disable MSIE and Chrome friendly error page -->
        <!-- a padding to disable MSIE and Chrome friendly error page -->
	</body>
</html>
