<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">JSON</h3>
            </div>
            <div class="box-body">
                <div class="main">
                    <div class="inner">

                        <form id="main_form" action="#" data-url="" method="POST">
                            <div id="jsoneditor"></div>
                            <script>
                                var text = {"name":"json\u5728\u7ebf\u7f16\u8f91\u5668","v1.0":"2014-07-02 22:05 \u5de5\u5177\u4e0a\u7ebf","v2.0":"2016-11-16 14:13 \u589e\u52a0php, go\u7c7b\u751f\u6210","v2.1":"2016-11-19 01:17 \u589e\u52a0java\u7c7b\u751f\u6210"};
                            </script>
                        </form>
                    </div>
                </div>
            </div>
            <div class="overlay" id="loading" style="display:none;">
                <i class="fa fa-refresh fa-spin"></i>
            </div>
        </div>
    </div>
</div>