<div class="row">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">JSON</h3>
            </div>
            <div class="box-body">
                <div class="main">
                    <div class="inner">

                        <form id="main_form" action="#" data-url="" method="POST">
                            <div id="jsoneditor"></div>
                            <script>
                                var text = {"name":"json在线编辑器"};
                            </script>
                        </form>
                    </div>
                </div>
            </div>
            <div class="overlay" id="loading" style="display:none;">
                <i class="fa fa-refresh fa-spin"></i>
            </div>
        </div>
    </div>
</div>