<div class="row">
	<div class="col-md-12">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">时间戳转换</h3>
			</div>
			<div class="box-body">
                <div class="main">
                    <div class="inner">
                        <p><span class="form_left">现在：</span><a id="js_timestamp_now" href="javascript:;">1572591945</a> 控制：<a id="js_timer_start" href="javascript:;" style="display: none;"><i class="glyphicon glyphicon-play"></i> 开始</a> <a id="js_timer_stop" href="javascript:;" style="color: #E74C3C;"><i class="glyphicon glyphicon-stop"></i> 停止</a>
                        </p>
                        <p>
                            <label class="form_left">时间戳</label>
                            <input type="text" class="text" id="js_timestamp" name="timestamp">
                            <select id="js_timestamp_unit" name="timestamp_unit">
                                <option value="s">秒(s)</option>
                                <option value="ms">毫秒(ms)</option>
                            </select>
                            <button id="js_convert_timestamp" type="button" class=" waves-effect">转换 <i class="glyphicon glyphicon-arrow-right"></i></button>
                            <input type="text" class="text" id="js_datetime" name="datetime"> <span>北京时间</span>
                        </p>
                        <p>
                            <label class="form_left">时间</label>
                            <input type="text" class="text" id="js_datetime_o" name="datetime_o"> <span>北京时间</span>
                            <button id="js_convert_datetime" type="button" class=" waves-effect">转换 <i class="glyphicon glyphicon-arrow-right"></i></button>
                            <input type="text" class="text" id="js_timestamp_o" name="timestamp_o">
                            <select id="js_timestamp_unit_o" name="timestamp_unit_o">
                                <option value="s">秒(s)</option>
                                <option value="ms">毫秒(ms)</option>
                            </select>
                        </p>
                        <!-- tool 10 | 13 -->
                        <h3>获取当前时间戳</h3>
                        <table class="tbl" width="100%" cellspacing="0" cellpadding="0">
                            <tbody>
                            <tr>
                                <td>Swift</td>
                                <td>
                                    <pre><code>NSDate().timeIntervalSince1970</code></pre>
                                </td>
                            </tr>
                            <tr>
                                <td>Go</td>
                                <td><pre><code>import (
  "time"
)
int32(time.Now().Unix())</code></pre>
                                </td>
                            </tr>
                            <tr>
                                <td>Java</td>
                                <td>
                    <pre><code>// pure java
(int) (System.currentTimeMillis() / 1000)</code></pre>
                                    <pre><code>// joda
(int) (DateTime.now().getMillis() / 1000)</code></pre>
                                </td>
                            </tr>
                            <tr>
                                <td>JavaScript</td>
                                <td>
                                    <pre><code>Math.round(new Date() / 1000)</code></pre>
                                </td>
                            </tr>
                            <tr>
                                <td>Objective-C</td>
                                <td>
                                    <pre><code>[[NSDate date] timeIntervalSince1970]</code></pre>
                                </td>
                            </tr>
                            <tr>
                                <td>MySQL</td>
                                <td>
                                    <pre><code>SELECT unix_timestamp(now())</code></pre>
                                </td>
                            </tr>
                            <tr>
                                <td>SQLite</td>
                                <td>
                                    <pre><code>SELECT strftime('%s', 'now')</code></pre>
                                </td>
                            </tr>
                            <tr>
                                <td>Erlang</td>
                                <td>
                                    <pre><code>calendar:datetime_to_gregorian_seconds(calendar:universal_time())-719528*24*3600.</code></pre>
                                </td>
                            </tr>
                            <tr>
                                <td>PHP</td>
                                <td>
                    <pre><code>// pure php
time()</code></pre>
                                    <pre><code>// Carbon\Carbon
Carbon::now()-&gt;timestamp</code></pre>
                                </td>
                            </tr>
                            <tr>
                                <td>Python</td>
                                <td><pre><code>import time
time.time()</code></pre>
                                </td>
                            </tr>
                            <tr>
                                <td>Ruby</td>
                                <td>
                                    <pre><code>Time.now.to_i</code></pre>
                                </td>
                            </tr>
                            <tr>
                                <td>Shell</td>
                                <td>
                                    <pre><code>date +%s</code></pre>
                                </td>
                            </tr>
                            <tr>
                                <td>Groovy</td>
                                <td>
                                    <pre><code>(new Date().time / 1000).intValue()</code></pre>
                                </td>
                            </tr>
                            <tr>
                                <td>Lua</td>
                                <td>
                                    <pre><code>os.time()</code></pre>
                                </td>
                            </tr>
                            <tr>
                                <td>.NET/C#</td>
                                <td>
                                    <pre><code>(DateTime.Now.ToUniversalTime().Ticks - 621355968000000000) / 10000000</code></pre>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                </div>
			</div>
			<div class="overlay" id="loading" style="display:none;">
              <i class="fa fa-refresh fa-spin"></i>
            </div>
		</div>
	</div>
</div>