<div class="row">
	<div class="col-md-7">
		<div class="box">
			<div class="box-header with-border">
				<h3 class="box-title">角色列表</h3>
			</div>
			<div class="box-body">
				<table class="table table-bordered text-center" id="DT">
					<thead>
						<tr>
    						<th>角色ID</th>
    						<th>角色名</th>
    						<th>操作</th>
						</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class="col-md-5">
		<div class="box">
			<div class="box-header with-border">
				<h3 class="box-title">添加新角色</h3>
			</div>
			<form id="roleform"  class="form-horizontal">
				<div class="box-body">
					<div class="form-group">
						<label for="" class="col-sm-3 control-label">角色名</label>
						<div class="col-sm-9">
							<input type="text" class="form-control" name="rolename" placeholder="请输入角色名" value="" maxlength="10" />
						</div>
					</div>
				</div>
				<div class="box-footer">
					<button type="submit" class="btn btn-info pull-right">提交</button>
				</div>
			</form>
		</div>
	</div>
</div>