<?php include(__DIR__.'/../layout/header.phtml');?>
<!-- plugins -->
<link href="<?php echo $staticRoot;?>/admin/js/plugins/jquery-chosen/jquery.chosen.min.css" rel="stylesheet">	
<script src="<?php echo $staticRoot;?>/admin/js/plugins/jquery-chosen/jquery.chosen.min.js"></script>
<script src="<?php echo $staticRoot;?>/admin/js/plugins/bootstrap-filestyle.min.js"></script>      

<div class="bg-white lter b-b wrapper-md">
  <h1 class="m-n font-thin h3">管理员管理</h1>
</div>
<div class="wrapper-md">

  <div class="ibox">
    <div class="ibox-title">
      <h5><?php echo empty($userInfo) ? '添加' : '编辑';?>管理员</h5>
	  <div class="ibox-tools">
        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
        <a class="dropdown-toggle"><i class="fa fa-wrench"></i></a>                                    
        <a class="close-link"><i class="fa fa-times"></i></a>
       </div>
    </div>
    <div class="ibox-content">
      <form class="form-horizontal">        
        <div class="form-group">
          <label class="col-sm-2 control-label" for="input-id-1">帐号</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" name="account" value="<?php echo empty($userInfo['account']) ? '' : $userInfo['account'];?>">
          </div>
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group">
          <label class="col-sm-2 control-label" for="input-id-1">姓名</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" name="name" value="<?php echo empty($userInfo['name']) ? '' : $userInfo['name'];?>">
          </div>
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group">
          <label class="col-sm-2 control-label">密码</label>
          <div class="col-sm-10">
            <input type="password" name="password" class="form-control">
          </div>
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group">
          <label class="col-sm-2 control-label">重复密码</label>
          <div class="col-sm-10">
            <input type="password" name="repassword" class="form-control">
          </div>
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group">
          <label class="col-sm-2 control-label">角色</label>
          <div class="col-sm-10">
            <select class="w-md chosen-select" name="role_id">
                <option value="0">请选择</option>
				<?php foreach($roleList as $role) { ?>	
				<option <?php if(!empty($userInfo) && $userInfo['role_id'] == $role['id']) echo 'selected="selected"';?> value="<?php echo $role['id'];?>"><?php echo $role['name'];?></option>						
				<?php } ?>
            </select>
          </div>
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group">
          <label class="col-sm-2 control-label">状态</label>
          <div class="col-sm-10">           
            <label class="i-switch bg-danger m-t-xs m-r">
              <input type="checkbox" <?php echo !isset($userInfo['status']) || $userInfo['status'] ? 'checked="checked"' : '';?> name="status">
              <i></i>
            </label>
          </div>
        </div>    
        <div class="hr-line-dashed"></div>
        <div class="form-group">
          <div class="col-sm-4 col-sm-offset-2">
            <button type="reset" class="btn btn-default">取消</button>
            <button type="submit" class="btn btn-primary">保存</button>
          </div>
        </div>
        <?php if(!empty($userInfo)) { ?>
        <input type="hidden" name="id" value="<?php echo $userInfo['id'];?>">
        <?php } ?>
      </form>
    </div>
  </div>
</div>

<script>
$(".chosen-select").chosen();
$("form").submit(function() {
	$.hook.ajax.post({
		"url":"/admin/edit",
		"data":$(this).serialize(),
		"success": function(json) {
			if(json.code == 1) {
				alert('操作成功 !');
				window.location.href="/admin/index";
				return false;
			}
			alert(json.msg);
		}
	});	
	return false;
});


</script>

<?php include(__DIR__.'/../layout/footer.phtml');?>