<div class="row">
	<div class="col-md-6">
        <form role="form" id="modifyPwdForm">
            <div class="box box-primary">
            	<!--
            	<div class="box-header with-border">
            		<h3 class="box-title">密码修改</h3>
            	</div>
            	-->
        		<div class="box-body">
        			<div class="form-group">
        				<label for="">旧密码：</label>
        				<input type="password" class="form-control" name="oldPwd" placeholder="请输入您现在使用的密码" />
        			</div>
        			<div class="form-group">
        				<label for="">新密码：</label>
        				<input type="password" class="form-control" name="newPwd" placeholder="请输入您的新密码" />
        			</div>
        			<div class="form-group">
        				<label for="">重复新密码：</label>
        				<input type="password" class="form-control" name="reNewPwd" placeholder="请再次输入您的新密码" />
        			</div>
        		</div>
        		<div class="box-footer">
        			<button type="submit" class="btn btn-primary">提交</button>
        		</div>
            </div>
        </form>
	</div>
</div>
