<div class="row">
	<div class="col-md-9">
		<div class="box">
			<div class="box-header with-border">
				<h3 class="box-title">管理员列表</h3>
			</div>
			<div class="box-body">
				<table class="table table-bordered text-center" id="DT">
					<thead>
						<tr>
    						<th>ID</th>
    						<th>账号</th>
    						<th>名称</th>
    						<th>最后登录</th>
    						<th>创建时间</th>
    						<th>角色</th>
    						<th>操作</th>
						</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class="col-md-3">
		<div class="box">
			<div class="box-header with-border">
				<h3 class="box-title">添加新账号</h3>
			</div>
			<form id="adminform">
				<div class="box-body">
					<div class="form-group">
						<label for="" class="control-label">账号：</label>
						<input type="text" class="form-control" name="account" placeholder="请输入账号" value="" maxlength="20" />
					</div>
					<div class="form-group">
						<label for="" class="control-label">名称：</label>
						<input type="text" class="form-control" name="nickname" placeholder="请输入姓名" value="" maxlength="20" />
					</div>
					<div class="form-group">
						<label for="" class="control-label">初始密码：</label>
						<input type="text" class="form-control" name="passwd" placeholder="请输入初始密码" value="" maxlength="20" />
					</div>
					<div class="form-group">
						<label for="" class="control-label">角色：</label>
    					<div class="checkbox">
							<?php foreach ($roleList as $item) { ?>
    						<label><input type="checkbox" name="roles" value="<?php echo $item['id']; ?>"> <?php echo $item['name']; ?></label>&nbsp;&nbsp;
							<?php } ?>
    					</div>
					</div>
				</div>
				<div class="box-footer">
					<button type="submit" class="btn btn-info pull-right">提交</button>
				</div>
			</form>
		</div>
	</div>
</div>